package exceptionTest;

/**
 * @author liupuyan
 * finally 被finally控制的语句体一定会执行
 * 一般用于释放资源
 */
public class demo6 {
	public static void main(String[] args) {
		method1();
	}

	private static void method1() {
		int a = 10;
		int b = 0;
		try {
			System.out.println(a / b);
		} catch (ArithmeticException e) {
			System.out.println("除数不能为0");
		} finally {
			System.out.println("finally");
		}
	}
	
	
}
